apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "external-dns-target-admission.fullname" . }}
rules:
  - apiGroups: ["v1"]
    resources: ["secrets"]
    verbs: ["get"]
